version: "3"
services:
  haproxy:
    image: hidupcloud/haproxy:1.5r1
    volumes:
      - ./certs/one.com.pem:/usr/local/etc/haproxy/one.com.pem
      - ./certs/two.com.pem:/usr/local/etc/haproxy/two.com.pem
      - ./certs/three.com.pem:/usr/local/etc/haproxy/three.com.pem
      - ./passwd/user1.pwd:/tmp/user1.pwd
      - ./passwd/user2.pwd:/tmp/user2.pwd
    environment:
      DEBUG: "true"
      HAPROXY_JSON_CFG: |
        {
          "domains":
            [
              {
                "name": "one",
                "url": [ "one.com", "onemore.com" ],
                "server": "localhost",
                "port": "8080",
                "basicauth": true,
                "userlist": "myusers"
              },
              {
                "name": "two",
                "url": [ "two.com" ],
                "server": "localhost",
                "port": "8081"
              },
              {
                "name": "three",
                "url": [ "three.com" ],
                "server": "localhost",
                "port": "8082"
              }
            ],
          "certs":
            [
              "/usr/local/etc/haproxy/one.com.pem",
              "/usr/local/etc/haproxy/two.com.pem",
              "/usr/local/etc/haproxy/three.com.pem"
            ],
          "userlist":
            [
              {
                "name": "myusers",
                "users":
                  [
                    {
                      "login": "useru",
                      "passtype": "insecure-password",
                      "passfile": "/tmp/user1.pwd"
                    },
                    {
                      "login": "users",
                      "passtype": "password",
                      "passfile": "/tmp/user2.pwd"
                    }
                  ]
              }
            ]
        }
